# Generated by Django 3.2.3 on 2021-06-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Producer_Name', models.CharField(max_length=30, verbose_name='Producer_Name')),
                ('size', models.CharField(max_length=5, verbose_name='Size')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('structure', models.CharField(max_length=100, verbose_name='Structure')),
                ('price', models.CharField(max_length=50, verbose_name='Price($)')),
                ('image', models.ImageField(upload_to='', verbose_name='Photo')),
            ],
        ),
    ]
