# Generated by Django 3.2.3 on 2021-06-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_element_producer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='Producer_Name',
            field=models.CharField(default='-', max_length=30, verbose_name='Producer_Name'),
        ),
    ]
