# Generated by Django 3.2.3 on 2021-06-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_element_producer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='title',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='element',
            name='Producer_Name',
            field=models.CharField(default='', max_length=30, verbose_name='Producer_Name'),
        ),
    ]
